name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - conda
  - mamba[version='>=1.5.9']
  - einops
  - h5py
  - huggingface_hub
  - lmdb
  - matplotlib
  - pandas
  - rocksdb
  - scipy
  - seaborn
  - scikit-image
  - tensorflow
  - timm
  - webdataset
  - opencv-python
  - openslide-python
  - openslide-bin
  - lmdb